Repository shopiroller/shopiroller-uikit-ios, pull requests merged in 2023-01, with the labels that each got.

#212 Feature/sr 1440
  Example/Podfile.lock
  Shopiroller/Classes/Extensions/UIViewControllerExtension.swift
  Shopiroller/Classes/Models/ResponseModels/ProductDetailResponseModel.swift
  Shopiroller/Classes/Models/VariantDataModel.swift
  Shopiroller/Classes/Models/VariantSelectionModel.swift
  Shopiroller/Classes/Models/Variation.swift
  Shopiroller/Classes/Scenes/Product Detail/ViewModel/SRProductDetailViewModel.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/ChildVariant/ChildVariantCollectionViewCell.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/ChildVariant/ChildVariantCollectionViewCell.xib
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/MainVariant/MainVariantCollectionViewCell.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/MainVariant/MainVariantCollectionViewCell.xib
  Shopiroller/Classes/Scenes/Product Detail/Views/SRProductDetailViewController.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/SRProductDetailViewController.xib
  Shopiroller/Classes/Shared/Views/CustomDiagonalLineView.swift
  Shopiroller/Classes/Support/az.lproj/Localizable.strings
  Shopiroller/Classes/Support/de.lproj/Localizable.strings
  Shopiroller/Classes/Support/en.lproj/Localizable.strings
  Shopiroller/Classes/Support/fr.lproj/Localizable.strings
  Shopiroller/Classes/Support/ru.lproj/Localizable.strings
  Shopiroller/Classes/Support/tr.lproj/Localizable.strings
Labels: enhancement

#211 Development
  Example/Podfile.lock
  Shopiroller/Classes/Extensions/UIViewControllerExtension.swift
  Shopiroller/Classes/Models/ResponseModels/ProductDetailResponseModel.swift
  Shopiroller/Classes/Models/VariantDataModel.swift
  Shopiroller/Classes/Models/VariantSelectionModel.swift
  Shopiroller/Classes/Models/Variation.swift
  Shopiroller/Classes/Scenes/Product Detail/ViewModel/SRProductDetailViewModel.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/ChildVariant/ChildVariantCollectionViewCell.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/ChildVariant/ChildVariantCollectionViewCell.xib
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/MainVariant/MainVariantCollectionViewCell.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/Cells/Variants/MainVariant/MainVariantCollectionViewCell.xib
  Shopiroller/Classes/Scenes/Product Detail/Views/SRProductDetailViewController.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/SRProductDetailViewController.xib
  Shopiroller/Classes/Scenes/Shopping Cart/Views/SRShoppingCartViewController.swift
  Shopiroller/Classes/Shared/Views/CustomDiagonalLineView.swift
  Shopiroller/Classes/Support/az.lproj/Localizable.strings
  Shopiroller/Classes/Support/de.lproj/Localizable.strings
  Shopiroller/Classes/Support/en.lproj/Localizable.strings
  Shopiroller/Classes/Support/fr.lproj/Localizable.strings
  Shopiroller/Classes/Support/ru.lproj/Localizable.strings
  Shopiroller/Classes/Support/tr.lproj/Localizable.strings
Labels: enhancement

#215 Bugfix/sr 1053 currency formatter change
  Example/Shopiroller/AppDelegate.swift
  Shopiroller/Classes/Extensions/CurrencyExtension.swift
  Shopiroller/Classes/Extensions/StringExtensions.swift
  Shopiroller/Classes/Helpers/CurrencyHelper.swift
  Shopiroller/Classes/Helpers/ECommerceUtil.swift
  Shopiroller/Classes/Scenes/Product Detail/ViewModel/SRProductDetailViewModel.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/SRProductDetailViewController.swift
  Shopiroller/Classes/Scenes/Shopping Cart/Views/Cells/ShoppingCartTableViewCell.swift
  Shopiroller/Classes/Shared/Models/ProductViewModel.swift
  Shopiroller/Classes/Shared/Views/Order Detail Product View/OrderDetailProductView.swift
  Shopiroller/Classes/Shared/Views/Product View/Views/ItemCollectionViewCell.swift
Labels: bug

#216 feature/SR-1482 variation update
  Shopiroller/Classes/Scenes/Product Detail/ViewModel/SRProductDetailViewModel.swift
  Shopiroller/Classes/Scenes/Product Detail/Views/SRProductDetailViewController.swift
  Shopiroller/Classes/Support/az.lproj/Localizable.strings
  Shopiroller/Classes/Support/de.lproj/Localizable.strings
  Shopiroller/Classes/Support/en.lproj/Localizable.strings
  Shopiroller/Classes/Support/fr.lproj/Localizable.strings
  Shopiroller/Classes/Support/ru.lproj/Localizable.strings
  Shopiroller/Classes/Support/tr.lproj/Localizable.strings
Labels: bug, enhancement

#217 fix - cell reload
  Shopiroller/Classes/Shared/Models/ProductViewModel.swift
  Shopiroller/Classes/Shared/Views/Product View/Views/ItemCollectionViewCell.swift
Labels: bug
